{
  "compatibilityLevel": 1601,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.137.1102.0 (24.10)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"CC_Trans\",\"Customer_data\",\"StartDate\",\"EndDate\",\"DimDate\",\"_measures\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "StartDate",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Date"
          }
        ],
        "expression": [
          "let",
          "    Source = #date(2023, 1, 1)",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "4ec2a288-792f-4670-b87f-7dad6b2cf839"
      },
      {
        "name": "EndDate",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Date"
          }
        ],
        "expression": [
          "let",
          "    Source = #date(2023, 12, 31)",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "b81f14c5-c6d1-4536-a550-792347e9820b"
      }
    ],
    "relationships": [
      {
        "name": "8fea961b-e85c-1784-d295-29f1ca13f85a",
        "fromColumn": "Week_Start_Date",
        "fromTable": "CC_Trans",
        "toColumn": "Dates",
        "toTable": "DimDate"
      },
      {
        "name": "2d2e1308-634f-2dfe-134e-0345d88ec9af",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Client_Num",
        "fromTable": "Customer_data",
        "toColumn": "Client_Num",
        "toTable": "CC_Trans"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "CC_Trans",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "changedProperties": [
          {
            "property": "Name"
          }
        ],
        "columns": [
          {
            "name": "Client_Num",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3ea75bf1-816e-4d14-98dc-091d6d0f4b7a",
            "sourceColumn": "Client_Num",
            "summarizeBy": "none"
          },
          {
            "name": "Card_Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "53cb7964-8a46-4c16-9029-d1a8e7f0e4cf",
            "sourceColumn": "Card_Category",
            "summarizeBy": "none"
          },
          {
            "name": "Annual_Fees",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fa8b9ead-f569-4bc9-aea8-141a940ed203",
            "sourceColumn": "Annual_Fees",
            "summarizeBy": "sum"
          },
          {
            "name": "Activation_30_Days",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "523aaa06-69a8-4689-98ba-7378cb9cbdf3",
            "sourceColumn": "Activation_30_Days",
            "summarizeBy": "sum"
          },
          {
            "name": "Customer_Acq_Cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cd0dd00e-9d0e-4aa9-8d5f-2cf2fb5aa73b",
            "sourceColumn": "Customer_Acq_Cost",
            "summarizeBy": "sum"
          },
          {
            "name": "Week_Start_Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "4b50d980-f773-4c18-9828-2dbd82ab591f",
            "sourceColumn": "Week_Start_Date",
            "summarizeBy": "none"
          },
          {
            "name": "Week_Num",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6b0d699d-5599-45b3-bf04-bae10a4022de",
            "sourceColumn": "Week_Num",
            "summarizeBy": "none"
          },
          {
            "name": "Qtr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bd484f90-c8c9-4c7d-9bab-f9bea03e97bd",
            "sourceColumn": "Qtr",
            "summarizeBy": "none"
          },
          {
            "name": "current_year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fd642cfc-b434-485d-802e-4a609e9f2443",
            "sourceColumn": "current_year",
            "summarizeBy": "sum"
          },
          {
            "name": "Credit_Limit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a3b93cfa-9174-4406-956d-49e41d84f382",
            "sourceColumn": "Credit_Limit",
            "summarizeBy": "sum"
          },
          {
            "name": "Total_Revolving_Bal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "677ad419-1ad0-4723-811a-e46b155e243e",
            "sourceColumn": "Total_Revolving_Bal",
            "summarizeBy": "sum"
          },
          {
            "name": "Total_Trans_Amt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1ff11a2f-a2b5-4abf-8aa4-214967fd9e49",
            "sourceColumn": "Total_Trans_Amt",
            "summarizeBy": "sum"
          },
          {
            "name": "Total_Trans_Vol",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c67262a8-476d-4b7a-818e-9acd64f42587",
            "sourceColumn": "Total_Trans_Vol",
            "summarizeBy": "sum"
          },
          {
            "name": "Avg_Utilization_Ratio",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6d5c12f4-7764-4f16-9e0f-2d6d7c9abaea",
            "sourceColumn": "Avg_Utilization_Ratio",
            "summarizeBy": "sum"
          },
          {
            "name": "Use Chip",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5139c9ee-6999-4284-86df-27ac64cdea20",
            "sourceColumn": "Use Chip",
            "summarizeBy": "none"
          },
          {
            "name": "Exp Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "34b18510-0ff8-4838-98fb-6febb22001c4",
            "sourceColumn": "Exp Type",
            "summarizeBy": "none"
          },
          {
            "name": "Interest_Earned",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "770cab63-e65f-402c-96df-31309a6e770f",
            "sourceColumn": "Interest_Earned",
            "summarizeBy": "sum"
          },
          {
            "name": "Delinquent_Acc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8a125894-b133-44e4-9492-9d730099e4d1",
            "sourceColumn": "Delinquent_Acc",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "1bef8bbf-8d33-4617-b44e-1b72a732fbc1",
        "partitions": [
          {
            "name": "CC_Trans",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PostgreSQL.Database(\"localhost\", \"CC_data\"),",
                "    public_credit_card = Source{[Schema=\"public\",Item=\"credit_card\"]}[Data],",
                "    #\"Changed Type with Locale\" = Table.TransformColumnTypes(public_credit_card, {{\"Week_Start_Date\", type date}}, \"en-GB\"),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Changed Type with Locale\", each true)",
                "in",
                "    #\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Customer_data",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "changedProperties": [
          {
            "property": "Name"
          }
        ],
        "columns": [
          {
            "name": "Client_Num",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d791397d-ef69-4a3e-9a1d-1ea268cd5652",
            "sourceColumn": "Client_Num",
            "summarizeBy": "none"
          },
          {
            "name": "Customer_Age",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f4be9874-c72a-44b1-8d7f-fb119051cc37",
            "sourceColumn": "Customer_Age",
            "summarizeBy": "sum"
          },
          {
            "name": "Gender",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0f7a1f08-bb03-4271-b639-d74ae3515d8e",
            "sourceColumn": "Gender",
            "summarizeBy": "none"
          },
          {
            "name": "Dependent_Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7761dad8-6cde-443b-bc49-23f7a906624c",
            "sourceColumn": "Dependent_Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Education_Level",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d2027937-7717-4900-afca-7c044b2b6397",
            "sourceColumn": "Education_Level",
            "summarizeBy": "none"
          },
          {
            "name": "Marital_Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4e868bce-e00f-45fc-9282-767c888f6202",
            "sourceColumn": "Marital_Status",
            "summarizeBy": "none"
          },
          {
            "name": "state_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dc4156b9-3071-4dc1-a569-ce6a508b128b",
            "sourceColumn": "state_cd",
            "summarizeBy": "none"
          },
          {
            "name": "Zipcode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "936679aa-f7e5-4e6b-80db-82f8110e3e87",
            "sourceColumn": "Zipcode",
            "summarizeBy": "sum"
          },
          {
            "name": "Car_Owner",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "38d1234b-7cc3-4ee6-b59e-d1c444c8b114",
            "sourceColumn": "Car_Owner",
            "summarizeBy": "none"
          },
          {
            "name": "House_Owner",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5c9a2e1b-91e1-4858-b700-c4596787b73d",
            "sourceColumn": "House_Owner",
            "summarizeBy": "none"
          },
          {
            "name": "Personal_loan",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "283257f7-2a6d-4f75-8789-3cbdde1b798d",
            "sourceColumn": "Personal_loan",
            "summarizeBy": "none"
          },
          {
            "name": "contact",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4ec9e23a-cbf9-4431-a11a-fec991f5cc11",
            "sourceColumn": "contact",
            "summarizeBy": "none"
          },
          {
            "name": "Customer_Job",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a8ac9f18-6b74-450a-89c8-3c0638e98f76",
            "sourceColumn": "Customer_Job",
            "summarizeBy": "none"
          },
          {
            "name": "Income",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "eac8892f-689a-4a2a-b4de-6b08a3afcdf7",
            "sourceColumn": "Income",
            "summarizeBy": "sum"
          },
          {
            "name": "Cust_Satisfaction_Score",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "97b44eff-f7e2-47d5-b2e2-8fec502d9564",
            "sourceColumn": "Cust_Satisfaction_Score",
            "summarizeBy": "sum"
          },
          {
            "name": "Age_Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "20867f00-696b-4a50-be4d-a53688132b95",
            "sourceColumn": "Age_Group",
            "summarizeBy": "none"
          },
          {
            "name": "Income_Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5b5085c1-e8df-43fc-9fee-469e64ab77af",
            "sourceColumn": "Income_Group",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "b96ea1f6-7a48-4590-9366-9abc24253439",
        "partitions": [
          {
            "name": "Customer_data",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PostgreSQL.Database(\"localhost\", \"CC_data\"),",
                "    public_customer = Source{[Schema=\"public\",Item=\"customer\"]}[Data],",
                "    Age_group = Table.AddColumn(public_customer, \"Age_Group\", each if [Customer_Age] < 20 then \"Bellow 20\" else if [Customer_Age] <= 30 then \"20-30\" else if [Customer_Age] <= 40 then \"31-40\" else if [Customer_Age] <= 50 then \"41-50\" else if [Customer_Age] <= 60 then \"51-60\" else 60),",
                "    #\"Added Custom\" = Table.AddColumn(Age_group, \"Custom\", each if [Income] < 40000 then \"Low\"",
                "else if [Income] <80000  then \"Medium\"",
                "else \"High\"),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Added Custom\",{{\"Custom\", \"Income_Group\"}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Renamed Columns\", each true)",
                "in",
                "    #\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DimDate",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Dates",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "7c07df2b-d187-4763-aa99-8724d6ccbd14",
            "sourceColumn": "Dates",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2d2b4659-206a-41d2-8175-e0426979dead",
            "sourceColumn": "Year",
            "summarizeBy": "none"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "def24a4e-a588-42d7-a658-3ff06eef4548",
            "sourceColumn": "Month",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b89a02ea-c5ac-41c1-8777-541781fa5a80",
            "sourceColumn": "Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "Week of Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7dcfc480-231d-409d-88be-c21f946082b9",
            "sourceColumn": "Week of Year",
            "summarizeBy": "none"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "ea4a513a-0da4-43a5-8161-3107b4f0ed86",
            "sortByColumn": "Month",
            "sourceColumn": "Month Name",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "4009641e-ecc1-4487-843a-e3402102fed2",
            "sortByColumn": "Quarter",
            "sourceColumn": "Quarter Name",
            "summarizeBy": "none"
          },
          {
            "name": "Week Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "06768456-f4d5-479b-90c8-e4f8b3080482",
            "sortByColumn": "Week of Year",
            "sourceColumn": "Week Name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "60d12d21-e062-403c-8fbb-dd11dc956972",
        "partitions": [
          {
            "name": "DimDate",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Duration = Duration.Days(EndDate-StartDate)+1,",
                "    #\"List of date\" = List.Dates(StartDate, Duration, #duration(1,0,0,0)),",
                "    #\"Converted to Table\" = Table.FromList(#\"List of date\", Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Converted to Table\",{{\"Column1\", \"Dates\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Dates\", type date}}),",
                "    #\"Inserted Year\" = Table.AddColumn(#\"Changed Type\", \"Year\", each Date.Year([Dates]), Int64.Type),",
                "    #\"Inserted Month\" = Table.AddColumn(#\"Inserted Year\", \"Month\", each Date.Month([Dates]), Int64.Type),",
                "    #\"Inserted Quarter\" = Table.AddColumn(#\"Inserted Month\", \"Quarter\", each Date.QuarterOfYear([Dates]), Int64.Type),",
                "    #\"Inserted Week of Year\" = Table.AddColumn(#\"Inserted Quarter\", \"Week of Year\", each Date.WeekOfYear([Dates]), Int64.Type),",
                "    #\"Inserted Month Name\" = Table.AddColumn(#\"Inserted Week of Year\", \"Month Name\", each Date.MonthName([Dates]), type text),",
                "    #\"Extracted First Characters\" = Table.TransformColumns(#\"Inserted Month Name\", {{\"Month Name\", each Text.Start(_, 3), type text}}),",
                "    #\"Added Quarter Name\" = Table.AddColumn(#\"Extracted First Characters\", \"Quarter Name\", each \"Q\"& Text.From([Quarter])),",
                "    #\"Added Week Name\" = Table.AddColumn(#\"Added Quarter Name\", \"Week Name\", each \"W\"& Text.From([Week of Year])),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Week Name\",{{\"Week of Year\", Int64.Type}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "_measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "b325bb15-1531-4696-8cb0-a02050115ddd",
        "measures": [
          {
            "name": "Revenue",
            "expression": "SUMX('CC_Trans', 'CC_Trans'[Total_Trans_Amt] + 'CC_Trans'[Interest_Earned] + 'CC_Trans'[Annual_Fees])",
            "formatStringDefinition": {
              "expression": [
                "SWITCH(",
                "    TRUE(),",
                "    SELECTEDMEASURE() > 1000000, \"$#,##0,,.0M\",",
                "    SELECTEDMEASURE() > 1000, \"$#,##0,.0K\"",
                ")"
              ]
            },
            "lineageTag": "46450bfc-19bd-42a4-9814-affc718d00fd"
          },
          {
            "name": "Previous Week Rev",
            "expression": [
              "",
              "CALCULATE(",
              "    [Revenue], ",
              "    FILTER(",
              "        ALL(DimDate),",
              "        DimDate[Week of Year] = MAX(DimDate[Week of Year])-1",
              "    )",
              ")"
            ],
            "formatStringDefinition": {
              "expression": [
                "SWITCH(",
                "    TRUE(),",
                "    SELECTEDMEASURE() > 1000000, \"$#,##0,,.00M\",",
                "    SELECTEDMEASURE() > 1000, \"$#,##0,.0K\"",
                ")"
              ]
            },
            "lineageTag": "9c57ff47-d680-4588-b0ea-27795a053acc"
          },
          {
            "name": "WoW %",
            "expression": [
              "",
              "VAR wow = DIVIDE(([Revenue]-[Previous Week Rev]), [Previous Week Rev])",
              "VAR Reslut = ",
              "IF(wow>=0, FORMAT(wow, \"0.#%\"), FORMAT(wow, \"0.#%\")&\" \")",
              "RETURN",
              "Reslut"
            ],
            "lineageTag": "93102d0b-0913-492b-b47c-a0339353d9dd"
          },
          {
            "name": "avg_rev",
            "expression": "AVERAGEX('CC_Trans', [Revenue])",
            "formatStringDefinition": {
              "expression": "\"#,###,.00K\""
            },
            "lineageTag": "c8852981-8bef-429a-ab3c-3288916afe3c"
          },
          {
            "name": "Total Customer",
            "expression": "COUNT('Customer_data'[Client_Num])",
            "formatStringDefinition": {
              "expression": [
                "SWITCH(",
                "    TRUE(),",
                "    SELECTEDMEASURE() < 999, \"###\",",
                "    SELECTEDMEASURE() < 100000, \"0.###,.0K\"",
                ")"
              ]
            },
            "lineageTag": "1b58cdcc-8b2a-4e24-986b-94d8b4cc9d3d"
          },
          {
            "name": "av",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Revenue]/[Total Customer]",
            "lineageTag": "3bc1a823-e4a7-4fb0-bb7f-41dccf049985"
          },
          {
            "name": "Total Trans Count",
            "expression": "SUM('CC_Trans'[Total_Trans_Vol])",
            "formatString": "0",
            "lineageTag": "ebd58b6e-eeda-461d-8835-d91d904205fc"
          },
          {
            "name": "Avg rev per trans",
            "expression": "DIVIDE([Revenue], [Total Trans Count])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "89f3d188-09fb-4e0c-811c-1d37dbc33a75"
          },
          {
            "name": "Female pct",
            "expression": [
              "",
              "VAR female = CALCULATE([Total Customer], Customer_data[Gender]=\"F\")",
              "VAR Total = [Total Customer]",
              "RETURN",
              "DIVIDE(female, Total)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "88e4b1d8-62d6-486f-b4b3-dfa572eed968"
          },
          {
            "name": "Male Pct",
            "expression": [
              "",
              "VAR male = CALCULATE([Total Customer], Customer_data[Gender]=\"M\")",
              "VAR Total = [Total Customer]",
              "RETURN",
              "DIVIDE(male, Total)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "73c0621b-60ba-4c39-8d67-25a8ef12bb11"
          },
          {
            "name": "Avg Credit Limit",
            "expression": "DIVIDE([Credit limit], [Total Customer])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "c940a059-1d56-4d6b-bad6-6f6b60500724"
          },
          {
            "name": "Credit limit",
            "expression": "SUM(CC_Trans[Credit_Limit])",
            "formatString": "0",
            "lineageTag": "9e63c22b-bcf3-4770-ac5c-59d1a8607171"
          },
          {
            "name": "SlicerCheck",
            "expression": [
              "",
              "    SWITCH(",
              "        TRUE(),",
              "        ISFILTERED(DimDate[Quarter Name]) || ",
              "        ISFILTERED(CC_Trans[Use Chip]) || ",
              "        ISFILTERED(Customer_data[Gender]) ||",
              "        ISFILTERED(Customer_data[Income_Group]) ||",
              "        ISFILTERED(CC_Trans[Card_Category]), 1,",
              "        0",
              "    )",
              ""
            ],
            "formatString": "0",
            "lineageTag": "d12d974e-9c3e-480b-bb92-d7aa5d26f7da"
          },
          {
            "name": "Acquation Cost",
            "expression": "SUM(CC_Trans[Customer_Acq_Cost])",
            "formatString": "0",
            "lineageTag": "af1ce2dc-45b8-4f48-81c5-5cb90dd39432"
          },
          {
            "name": "Revolving_Bucket",
            "expression": [
              "",
              "    VAR bucketSize = (MAX(CC_Trans[Total_Revolving_Bal]) - MIN(CC_Trans[Total_Revolving_Bal])) / 10",
              "    VAR Revolving_balance = SELECTEDVALUE(CC_Trans[Total_Revolving_Bal])",
              "    VAR lowerBound = INT((Revolving_balance - MIN(CC_Trans[Total_Revolving_Bal])) / bucketSize) * bucketSize + MIN(CC_Trans[Total_Revolving_Bal])",
              "    VAR upperBound = lowerBound + bucketSize",
              "    VAR lowerBoundFormatted = IF(MOD(ROUND(lowerBound / 1000, 1), 1) = 0, FORMAT(ROUND(lowerBound / 1000, 1), \"0\"), FORMAT(lowerBound / 1000, \"0.0\"))",
              "    VAR upperBoundFormatted = IF(MOD(ROUND(upperBound / 1000, 1), 1) = 0, FORMAT(ROUND(upperBound / 1000, 1), \"0\"), FORMAT(upperBound / 1000, \"0.0\"))",
              "    RETURN",
              "        lowerBoundFormatted &  upperBoundFormatted ",
              ""
            ],
            "lineageTag": "45261346-e947-4a24-a602-755b6ce3fe2f"
          },
          {
            "name": "Pct fo customer",
            "expression": [
              "",
              "DIVIDE([Total Customer], ",
              "CALCULATE([Total Customer], ALL(CC_Trans)))"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "aeb4a531-cf0c-4eb4-84ac-0419d15ddea7"
          }
        ],
        "partitions": [
          {
            "name": "_measures",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}